# -*- coding: utf-8 -*-
"""
merge_bib.py — individual/ 폴더의 개별 .bib 들을 합쳐 publications.bib 생성.

워크플로우:
  1) 논문 홈페이지/Scholar/Zotero에서 받은 BibTeX를 cv/citations/individual/ 에 저장
     (파일 1개에 1편 권장, 여러 편 들어 있어도 됨)
  2) python merge_bib.py
  3) → publications.bib 재생성 (DOI 기준 중복 제거, 출판시기 오름차순 정렬)

각 항목의 원문(raw BibTeX)을 그대로 보존하고 순서만 정렬/중복제거합니다.
"""
import re, glob, os

HERE  = os.path.dirname(os.path.abspath(__file__))
INDIV = os.path.join(HERE, "individual")
OUT   = os.path.join(HERE, "publications.bib")

MONTHS = {m: i for i, m in enumerate(
    ["jan","feb","mar","apr","may","jun","jul","aug","sep","oct","nov","dec"], 1)}

HEADER = """% =====================================================================
% publications.bib  —  AUTO-GENERATED by merge_bib.py (do not edit by hand)
% 원본 개별 BibTeX: cv/citations/individual/*.bib  → 수정은 거기서.
% 정렬: 출판시기 오름차순(오래된→최신). 중복은 DOI 기준 제거.
% =====================================================================

"""

def split_entries(text):
    """Return list of raw '@type{...}' blocks via brace matching."""
    out, i = [], 0
    while True:
        at = text.find("@", i)
        if at < 0:
            break
        b = text.find("{", at)
        if b < 0:
            break
        depth, j = 0, b
        while j < len(text):
            if text[j] == "{": depth += 1
            elif text[j] == "}":
                depth -= 1
                if depth == 0:
                    break
            j += 1
        out.append(text[at:j + 1])
        i = j + 1
    return out

def field(raw, name):
    m = re.search(r"\b" + name + r"\s*=\s*\{(.*?)\}\s*[,}\n]", raw, re.I | re.S)
    if m:
        return m.group(1).strip()
    m = re.search(r"\b" + name + r"\s*=\s*([A-Za-z0-9]+)\s*[,}\n]", raw, re.I)
    return m.group(1).strip() if m else ""

def citekey(raw):
    m = re.search(r"@\w+\s*\{\s*([^,]+),", raw)
    return (m.group(1).strip() if m else "").lower()

def norm_doi(s):
    s = re.sub(r"(?i)^\s*https?://(dx\.)?doi\.org/", "", s.strip())
    return s.lower().rstrip(" .")

def get_doi(raw):
    """DOI from doi field; fall back to citekey if it looks like a DOI (KOSERT exports)."""
    d = field(raw, "doi")
    if d:
        return norm_doi(d)
    ck = citekey(raw)
    return norm_doi(ck) if re.match(r"^10\.\d{4,9}/", ck) else ""

def month_num(raw):
    mo = field(raw, "month").lower()[:3]
    if mo in MONTHS: return MONTHS[mo]
    if mo.isdigit(): return int(mo)
    m = re.search(r"\b\d{4}-(\d{2})", field(raw, "date"))   # ISO date fallback
    return int(m.group(1)) if m else 0

def first_author_last(raw):
    au = field(raw, "author")
    if not au: return ""
    first = au.split(" and ")[0].strip()
    return (first.split(",")[0] if "," in first else first.split()[-1]).lower()

def main():
    files = sorted(glob.glob(os.path.join(INDIV, "*.bib")))
    seen, kept, warn = {}, [], []
    for f in files:
        for raw in split_entries(open(f, encoding="utf-8").read()):
            doi = get_doi(raw)
            dkey = doi or ("title::" + field(raw, "title").lower())
            if dkey in seen:
                warn.append(f"  [dup] DOI {doi or '(no doi)'} — {os.path.basename(f)} (이미 {seen[dkey]} 에 있음, 건너뜀)")
                continue
            seen[dkey] = os.path.basename(f)
            sortk = (int(field(raw, "year") or 0), month_num(raw), first_author_last(raw), citekey(raw))
            kept.append((sortk, raw.strip()))
    kept.sort(key=lambda x: x[0])
    with open(OUT, "w", encoding="utf-8") as w:
        w.write(HEADER)
        for _, raw in kept:
            w.write(raw + "\n\n")
    print(f"merged {len(kept)} entries from {len(files)} file(s) -> publications.bib")
    for k, _ in kept:
        print(f"  {k[0]} {k[1]:>2} | {k[3]}")
    if warn:
        print("WARNINGS (중복 — 한쪽 파일만 남기세요):")
        print("\n".join(warn))

if __name__ == "__main__":
    main()
